### PR TITLE
Changed behavior when using hex only output.

### PR DESCRIPTION
**Pull request by RingingResonance**
Changed behavior so that when using hex only output the compiler will add in the appropriate filler data between ORG's so as to match memory mapping when writing to ROMs.
Note that this is my first time playing with python.

### CODE REVIEW

**Comment by ept221** [comment]
For my application, I actually need the "filler data" to be non-existent, as the output of this assembler gets fed into another tool of mine. However you raise a good point, there should be an option to print the entire memory map. However, it really should be NOPs not HLTs like you're doing. At some point I'm going to rewrite the assembler to handle other number formats and make things generally cleaner. I'll add the option you're requesting at that point, but I can't merge this, as it would break my current workflow. Thank you for pointing that out, though!

**Comment by ept221** [comment]
@RingingResonance Just wanted to let you know that the code now adds filler data like you requested (NOPs not HLTs, but this is easy to change if you want). Additionally the assembler now supports strings, and numbers in hex, decimal, and binary, and negative numbers. The `-c` option compresses things and won't include the filler data, (and the `-s` option uses this for readability), however by default the filler data is now included.

**Comment by RingingResonance** [comment]
holy cow! You've been busy! Thanks for letting me know! I will try it out
at some point. Not many good and open source 8085/Z80 assemblers around
that run on modern systems!

**Comment by RingingResonance** [comment]
Maybe in the future it could also support some kind of #include file.asm
functionality?

**Comment by ept221** [comment]
Yeah, that is definitely on my list, along with user defined macros. I also want to handle multiplication and division in expressions, which means writing a proper recursive decent parser, which will be a bit more involved.

**Pull request closed without merging**
